FROM daiweilu/starboard-http-server-node-modules:v<%= baseimage_version %>

ADD package.json /app/

ADD src /app/src
ADD config /app/config
ADD template /app/template
ADD static /app/static

EXPOSE 10000
CMD ["node", "--harmony_destructuring", "--harmony_default_parameters", "src/index.js"]
